version: '3'
services:
  laravel.test:
    build:
      context: ./docker/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - jo
  jo:
    image: 'jo/jo-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      jo_ROOT_PASSWORD: '${DB_PASSWORD}'
      jo_ROOT_HOST: '%'
      jo_DATABASE: '${DB_DATABASE}'
      jo_USER: '${DB_USERNAME}'
      jo_PASSWORD: '${DB_PASSWORD}'
      jo_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-jo:/var/lib/jo'
      - './vendor/laravel/sail/database/jo/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - joadmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  sail-jo:
    driver: local
